language: node_js
node_js:
- 0.12.4
sudo: false
after_success:
- npm run report-coverage
deploy:
  provider: npm
  email: d2ltravisdeploy@d2l.com
  api_key:
    secure: KCMunMeKdmf+UTkDQSme9O5oANYXqNUzIy2kxkDJLeAc9Fk9UG/TIrNhowbFRjhcVNbtf6hZwV8T+Q1qTT2wovqo5Zi4yNMJw7GS2OfwV2GQi0iOmN3sx7vaHXbxFjNbjEn96KfcX0fHii8vUlEiH5MQQBflysVweohpoIbAWLHQ5hWB5XCB/8YXlH9y6WncCc05lpb1AVcLvVg64UecYc0wuYK7n24wvKQ1mxj8xeOOeQ4y/4aBHDkVVzMB1rbOnhNs+xELoCIlwmFtleuaUX7e6aB2sQwANMWSelHz3jgn1HyxLhh6fY9eqB4IvlcxJToss2kGqnEz6En4zf9/621pHZEHgB0hN/k/ihG1k4BWq3lT+jX8T9eBnA2+2rVDztcpPjS7rG6mS3HxCFOxX4ufBeF1DRjdk2wepaoVvLoR5/qHCUnjiXI/n+l5YjTKUW7UhAc9H8EZTeWa9dHYXT1tRBIbah4Yki6NM+d3e9vqd7Pi1kPz0Yo12GZPSUS/8ZBMbJkuffwuEa0kWSxjcTFYLNDA8zmGuM7MRhTVYnUupZ0c1CojszxhSWrRvHlIniSs1BeZ4vU/3KDR51jaDH1wUZRD5pKEcXHsWGv3IkBD/OKyTck6smMDcWQ4XmToD/qdU837jzXpUqvDbiGJpW7cbqc7XA/nw0oyX89kDJA=
  on:
    tags: true
    repo: Brightspace/frau-jwt
