language: node_js
node_js:
- 0.12.4
sudo: false
after_success:
- npm run report-coverage
deploy:
  provider: npm
  email: d2ltravisdeploy@d2l.com
  api_key:
    secure: Ux4EGxvTC/FdXdPsPpOzxp7iroY3+tjCC4PLIfzgMiAeGyeXdxL51+Cv8RthlXhjjbvhJ23b21TXBcajHEtfRYpJ7SAVSZadD+UqEPU5jjE5FlmsWScdO95LcukUg6V9LfA37dluo2/u9i5iX6FYH53dcVJwFY2+00NI9ZToQF3FsDUPTmM1gpIX8r0PA2QXXtO42pDzCgmzcfQtEa/qRJZ8R+9W2FqR555RZT8WTtinwt5RvzrxepjKbdji/Fswkj6yrb1EF/vIwcPYBigLeKcBA/V1DkS/UrzVOtcTH2VeiKWiLlTSS/nwTx7I441+jzUPYgp7Iy4Bo/iF4/OzRukLgtuXahWnKp9Q70r0P9rdaM2daJ5EOtcsvQkdsR33n2XQ56As9O5Bdx7g1g77vNjqNRvQxE06uTYiCF6C3HlCxcs5lSCjb49E6UxXIzEQ4scp2wgSg6a89uJsyjTc/sQz7dOGT1hJCcHBfzDJlCjEBGOCGklX/rQZWlpmb5aAuthJ2X2pjuOcjupYjZfil00JYQ5liB4DzpcvDIYKlkdpGeh7pUHhO0zara5ZCw0wkZq8s7inGXrcwVLZ02yWdaFW2Mmv0wVWIIG6qzTx81K7nDQEGzvv+YDG3jOYC7QklwucE1RW4WDLP726ZAhcZueSvwysZoSP4h85Z41N3Rs=
  on:
    tags: true
    repo: Brightspace/frau-jwt
